FROM node:18-alpine
WORKDIR /app

# Add ARG statements near the top
ARG STRAPI_API_TOKEN
ARG NEXT_PUBLIC_STRAPI_API_URL
ARG NEXT_PUBLIC_STRAPI_TOKEN

# Copy package files
COPY package*.json ./
COPY .npmrc ./

# Install dependencies with clean install
RUN npm ci && npm install sharp


# Create necessary directories and set permissions
RUN mkdir -p .next && \
    chown -R node:node /app

# Set environment variables
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=development
ENV NEXT_PUBLIC_STRAPI_API_URL=${NEXT_PUBLIC_STRAPI_API_URL}
ENV NEXT_PUBLIC_STRAPI_URL=${NEXT_PUBLIC_STRAPI_URL}
ENV STRAPI_INTERNAL_URL=http://strapi:1337
ENV STRAPI_API_TOKEN=${STRAPI_API_TOKEN}
ENV NEXT_PUBLIC_STRAPI_TOKEN=${STRAPI_API_TOKEN}

USER node
EXPOSE 3000
CMD ["npm", "run", "dev"]